# Generated by Django 2.2.13 on 2021-12-11 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211210_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('BLACK', 'black'), ('BROWN', 'brown'), ('YELLOW', 'yellow'), ('RED', 'red'), ('GREEN', 'green'), ('PURPLE', 'purple'), ('UNKNOWN', 'unknown')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('BLACK', 'black'), ('BROWN', 'brown'), ('BLONDE', 'blonde'), ('RED', 'red'), ('WHITE', 'white'), ('BALD', 'bald')], max_length=32),
        ),
        migrations.CreateModel(
            name='People_film',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.People')),
                ('films', models.ManyToManyField(blank=True, related_name='film', to='app.Film')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.people',),
        ),
    ]
