# Generated by Django 2.2.13 on 2021-12-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211210_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people_film',
            name='films',
            field=models.ManyToManyField(blank=True, to='app.Film'),
        ),
    ]
