# Generated by Django 2.2.13 on 2021-12-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211211_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='films', to='app.Director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.ManyToManyField(blank=True, related_name='films', to='app.Producer'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True),
        ),
    ]
