# Generated by Django 2.2.13 on 2021-12-11 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211211_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, related_name='films', to='app.People'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='films', to='app.Director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='planets',
            field=models.ManyToManyField(blank=True, null=True, related_name='films', to='app.Planet'),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.ManyToManyField(blank=True, null=True, related_name='films', to='app.Producer'),
        ),
    ]
