# Generated by Django 2.2.13 on 2021-12-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211211_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='episode_id',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='people_film',
            name='films',
            field=models.ManyToManyField(to='app.Film'),
        ),
    ]
