# Generated by Django 2.2.13 on 2021-12-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211211_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='episode_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
