# Generated by Django 2.2.13 on 2021-12-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211211_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='episode_id',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
