# Generated by Django 2.2.13 on 2021-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211211_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
